In [ ]:
import pandas as pd

In [ ]:
loan_df = pd.read_csv("/Users/vijayrajan/Downloads/loan_data_set.csv")

In [ ]:
loan_df.head()

In [ ]:
import numpy as np

In [ ]:
np_arr_1_5 = np.array([1,2,3,4,5])

In [ ]:
print(np_arr_1_5)

In [ ]:
np_arr_zeros = np.zeros((2,3,4))

In [ ]:
np_arr_zeros

In [ ]:
np_arr_ones = np.ones((2,3,4))

In [ ]:
np_arr_ones

In [ ]:
np_arr_empty = np.empty((5,6))
np_arr_empty

In [ ]:
np_arr_arange = np.arange(20)
np_arr_arange

In [ ]:
np_arr_arange.reshape(2,10)

In [ ]:
np_arr_linspace = np.linspace(0,10,17)
print(np_arr_linspace)

In [ ]:
oneD_arr = np.arange(72)
oneD_arr

In [ ]:
twoD_arr = oneD_arr.reshape(8,9)
twoD_arr

In [ ]:
threeD_arr = np.arange(24).reshape((2,3,4))
print(threeD_arr)

In [ ]:
twoD_arr.ndim

In [ ]:
threeD_arr.ndim

In [ ]:
threeD_arr.shape

In [ ]:
threeD_arr.size

In [ ]:
threeD_arr.dtype

In [ ]:
twoD_arr.dtype

In [ ]:
np_arr_empty.dtype

In [ ]:
np_array_of_string = np.array(("Vijay", "Shuba", "Kavya", "Keertana", "Nandini", "Rajesh", "Avi", "Sunil", "Lakshmi"))

In [ ]:
print(np_array_of_string.dtype)
print(np_array_of_string.shape)
print(np_array_of_string.ndim)
print(np_array_of_string.size)

In [ ]:

print(np_arr_1_5.dtype)
print(np_arr_1_5.shape)
print(np_arr_1_5.ndim)
print(np_arr_1_5.size)


In [ ]:
print(np_array_of_string.itemsize)

In [ ]:
print(np_arr_1_5)
print(np_arr_1_5.dtype)
print(np_arr_1_5.itemsize)
print(np_arr_1_5.shape)


In [ ]:
print(np_arr_1_5.data[0])

In [ ]:
np_zeroD_arr = np.array(24)

In [ ]:
print(np_zeroD_arr)

In [ ]:
#print(np_zeroD_arr.data)
np_oned_array = np.array([1,2,3,4,5])
print(np_oned_array)

In [2]:
np_2d_array = np.array([[1,2,3,4,5],[100,101,102,103,104]])
print(np_2d_array)
#np.array([[1,2,3,4,5],[100,101,102,103]]) - the two sub arrays do not have the same length and numpy barfs

[[  1   2   3   4   5]
 [100 101 102 103 104]]


In [ ]:
np_3d_array = np.array([[[1,2,3,4,5], [0,9,8,7,6]],[[100,101,102,103,104], [11,12,13,14,15]], [[6,7,8,9,10], [33,44,55,66,77]]])
print(np_3d_array)

In [ ]:
print(np_3d_array.shape)

In [ ]:
print(np_3d_array.ndim)

In [ ]:
np_arr_24 = np.array([x for x in range(1,25)])
print(np_arr_24)

In [ ]:
np_arr_24.reshape(3,8)

In [ ]:
np_arr_24.reshape(2,3,4)

In [ ]:
np_arr_2_3_4 = np_arr_24.reshape(2,3,-1)

In [ ]:
np_arr_2_3_4.reshape(-1)
test = np_arr_24.reshape(3,2,-1)

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([7,8,9])

C = np.add(A,B)

print("-----A-------")
print(A)
print("-----B-------")
print(B)
print("-----C-------")
print(C)

In [ ]:
D = np.subtract(A,B)
print(D)

In [ ]:
E = np.subtract(B,A)
print(E)

In [ ]:
print("-----A-------")
print(A)
print("-----B-------")
print(B)
np.multiply(A,B)

In [ ]:
print("-----A-------")
print(A)
print("-----B-------")
print(B)
F=np.multiply(B,A)
G=np.multiply(A,B)

print(F)
print(G)

In [ ]:
print("-----A-------")
print(A)
print("-----B-------")
print(B)

F=np.divide(B,A)
G=np.divide(A,B)
print("--------------\n\n")
print(F)
print("--------------\n")


print(G)

In [ ]:
print("-----A-------")
print(A)
print("-----B-------")
print(B)

H = np.power(B,2)
I = np.power(A,2)
J = np.power(A,B)
K = np.power(B,A)
print("--------------\n")
print(H)
print("--------------\n")
print(I)
print("--------------\n")
print(J)
print("--------------\n")
print(K)

In [ ]:
np_arr_24 = np.array([x for x in range(1,25)])

In [ ]:
np.where(np_arr_24%2==0, 'Even', 'Odd')

In [ ]:
condlist = [np_arr_24<12,np_arr_24>12]

In [ ]:
choicelist = [np_arr_24**2,np_arr_24**0.5]

In [ ]:
np.select(condlist, choicelist, default= np_arr_24)

In [ ]:
#3.11 is where to start in https://lms.simplilearn.com/courses/2772/Data-Science-with-Python/syllabus

In [ ]:
np.amin(np_arr_24)

In [ ]:
np_arr_24

In [ ]:
np_arr_24.reshape(3,8)

In [ ]:
x = np.array([[1,3,5],[6,8,2],[7,9,4]])
print(x)
print("----")
print(np.amin(x))
print("----")
print(np.amin( x, axis=0))
print("----")
print(np.amin( x, axis=1))
print("----")
print(np.amax( x, axis=0))
print("----")
print(np.amax( x, axis=1))
print("----")
print(np.median( x, axis=0))
print("----")
print(np.median( x, axis=1))
print("--MEAN--")
print(np.mean( x, axis=0))
print("----")
print(np.mean( x, axis=1))
print("----")
print(np.median(x))
print("----")
print(np.mean(x))
print("----")
print(np.std(x))
print("--STD--")
print(np.std(x, axis = 0))
print("--VAR--")
print(np.var(x, axis = 0))

print("----")
print(np.std(x, axis = 1))
print("----")
print(np.var(x, axis = 1))
print("----")


print("--PERCENTILE--")
print(np.percentile(x,55))
print("----")

print(np.floor(x))


In [ ]:
np.amin(x, axis=0)

In [ ]:
import pandas as pd
import numpy as np

degree = np.array([0,30,45,62,90,120, 135, 150,180])
radians = degree * np.pi/180
print (degree)
print(np.round(radians,2))
print(np.round(np.sin(radians),2))
print(np.round(np.cos(radians),2))

In [ ]:
print("test")

In [ ]:
import pandas as pd
import numpy as np

def get_dim_and_size(arr):
    print("\n\n\n ----------------------------------------")
    print(arr)
    print("ndim " + str(np.ndim(arr)))
    print("size " + str(np.size(arr)))
    shape_arr = np.shape(arr)
    print("shape " + str(shape_arr))
    print(" ----------------------------------------\n\n")
        
def slice_arrays(arr):
    print(arr[0:,-1:])
        
        
arr1d = np.array([1,2,3,4,5])
arr2d = np.array([[1,2,3],[4,5,6]])
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

get_dim_and_size(arr1d)
get_dim_and_size(arr2d)
get_dim_and_size(arr3d)


print(arr1d[0])
print(arr1d[-3])
print(arr2d[1,2])
print(arr3d[2,1,-2])

slice_arrays(arr2d)
print(arr2d[0,-1])




In [ ]:
import pandas as pd
l = [(x+1) for x in range(5)]
s = pd.Series(l)
print(s)
print(l[3])
s = pd.Series(l, index=['a','b','c','d','e'])
print(s)

#dictionary
d = {'f':1,'g':2,'h':3}
s = pd.Series(d)
print(s)

s = pd.Series(d,index=['g','f'])
print(s)


In [ ]:
import pandas as pd
l = [(x+1) for x in range(5)]
s = pd.Series(l)
print(s)
print(l[3])
s = pd.Series(l, index=['a','b','c','d','e'])
print(s)

#dictionary
d = {'f':1,'g':2,'h':3}
s = pd.Series(d)
print(s)

s = pd.Series(d,index=['g','f'])
print(s)


In [ ]:
#3.16 - querying with pandas
import pandas as pd
import numpy as np

s = pd.Series([(x*x+x+1) for x in range(1,11)])
print(s)
print(s.iloc[0])
print(s.iat[0])
print(s[3:8])
print(s[-8:-3])
#print(s.where(s%3==0))
print("\n\n---\n")
k = pd.Series.copy(s)
s.where(s%3==0, inplace=True)
print(s)
print(s.dropna())
print(k.where(k%3==0, np.sqrt(k)))
print("\n\n---\n")

print(s.where(s%3==0,'Vijay\'s prime'))





In [ ]:
import pandas as pd
import numpy as np


df = pd.DataFrame()
type(df)

df = pd.read_csv('experto_dhobiwalla_analysis_2pct.csv')

df.head()
df.tail()
df.iloc[20919].rule
#read csv based on chunk size and iterate cant be done here

df2 = df[df['order_count'] > 50.0]
df2.set_index(['rule','order_count','revenue'], inplace=True)
#df2
#df.index
print(df2.loc['Day_of_Week=Thu and Service=Dry_Cleaning and Total_Garment_bucket=bucket_1 and Store_Name=DOMLUR'])


df2.cov()




In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('experto_dhobiwalla_analysis_2pct.csv')

for index,row in df.iterrows():
    print(row['rule'],row['level'],  index)


In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('experto_dhobiwalla_analysis_2pct.csv')

print(df.apply(lambda row:str(row["level"]) + " "+  row["rule"] + " " +  str(round(row['revenue'] / row['order_count'],2)), axis=1))



In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('experto_dhobiwalla_analysis_2pct.csv')

df.columns
print(df[['revenue', 'order_count']])
#df[['order_count','revenue']].plot(x='revenue', y='order_count', legend=True,kind='scatter')
df[['level','order_count','revenue']].plot(x='level', y='order_count', legend=True,kind='scatter')



In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('experto_dhobiwalla_analysis_2pct.csv')

df2 = df[df['rule'].str.contains('Day_of_Week')]
df2

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('experto_dhobiwalla_analysis_2pct.csv')

print(df.columns)
print(df[['revenue', 'order_count']])
#df[['order_count','revenue']].plot(x='revenue', y='order_count', legend=True,kind='scatter')
df[['level','order_count','revenue']].plot(x='level', y='order_count', legend=True,kind='scatter')




In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style
%matplotlib inline

randomnumbers = np.random.rand(100)
print(randomnumbers)
k = pd.Series(randomnumbers)
print(k)
style.use('ggplot')
plt.plot(randomnumbers, 'g', label='line one', linewidth=2)
plt.xlabel('Range')
plt.ylabel('Numbers')
plt.title('Plot of random numbers')

plt.legend()
plt.show()


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style
%matplotlib inline



In [ ]:
r = [1,2,3,4,5]
r.append(8)
s=np.array(r)
s = np.append(s,9)
s

In [ ]:
import seaborn as sns
import pandas as pd

sns.set_theme()
fmri = sns.load_dataset("fmri")
print(fmri.columns)
for x in fmri.columns:
    print(x, fmri[x].unique())

#d = fmri['subject'].unique()
sns.relplot(data=fmri, kind="line", x="timepoint", y="signal",col="region", hue="event", style="event")

In [271]:
#scipy
import numpy as np
#from scipy import linalg
import scipy.linalg as blah

#   x   +   y   =    30
#  4x   +  9y   =   150 
coefficients  = np.array([[1,1],[4,9]])
outputs_of_eq = np.array([30,150])

blah.solve(coefficients,outputs_of_eq)



array([24.,  6.])

In [272]:
#scikit-learn

import numpy as np
from sklearn import datasets
import pandas as pd

data = datasets.load_breast_cancer()
print(data.keys())
data['data']

df = pd.DataFrame(data.data, columns=data.feature_names)
df.head()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [273]:
print ("Vijay")

Vijay


In [1]:
from random import random
from random import randint
from random import seed
import numpy as np

seed(37)

#function to generate an array of random numbers
def generate_array_of_random(array_size, low_range, high_range):
    arr = np.random.randint(low_range,high_range,array_size)
    return np.sort(arr)

#function that runs the trials for a given array_size
def run_experiment(array_size, trial_count):
    count_inciding_birthday_found = 0
    #loop for 'trial_count' times we run the 
    for trials in range(1, trial_count):
        arr = generate_array_of_random(array_size, 1, 365) #365 days the year
        if (len(np.unique(arr)) < array_size):
            count_inciding_birthday_found = count_inciding_birthday_found + 1
    return round(100 * count_inciding_birthday_found / trial_count, 1)

#########
#main code
array_size = 23   # the proposed answer to check if we can get a 50% chance of coincidence of birthday
trials_count = 100 # how many times to form a array of 'array_size' 
experiment_count = 300

arr = np.array([])
for x in range(0,experiment_count):
    arr = np.append(arr,run_experiment(array_size, trials_count))
        
print("For an array size of " + str(array_size) + \
      ", a trial count of " + str(trials_count) + \
      " and an experiment count of " + str(experiment_count) + \
      ", the mean is " + str(round(np.mean(arr),1)) +\
      " with a std-dev of " + str(round(np.std(arr),1)))



For an array size of 23, a trial count of 100 and an experiment count of 300, the mean is 50.6 with a std-dev of 4.8


In [15]:
# Create a dictionary
my_dict = {
    "name": "John",
    "age": 25
}

# Get the keys of the dictionary
keys = my_dict.keys()

# Convert the keys to a list
keys_list = list(keys)

# Print the keys list
print(keys_list)

['name', 'age']
